server:
  port: 8080

spring:
  application:
    name: ArbMonitorAPI
  
  datasource:
    url: jdbc:h2:file:./data/arbmonitor;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate  # Changed from 'update' to 'validate' - schema managed by Flyway
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  # Flyway configuration for database migrations
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    clean-disabled: true  # Prevent accidental data deletion
        
  web:
    resources:
      add-mappings: false
      
  mvc:
    throw-exception-if-no-handler-found: true

# Application specific configuration
app:
  apify:
    token: ${APIFY_TOKEN:your-apify-token-here}
    org-id: ${APIFY_ORG_ID:your-apify-org-id-here}
  openai:
    api-key: ${OPENAI_API_KEY:your-openai-api-key-here}
  media:
    base-path: ./media
    storage:
      path: ${MEDIA_STORAGE_PATH:./media}
  video:
    frame-interval: 0.5  # Extract 1 frame every 0.5 seconds for better text capture
    max-frames: 120      # Maximum frames to extract per video (60s video = 120 frames)
    cleanup-frames: true # Delete individual frames after OCR processing

  cors:
    allowed-origins: "http://localhost:3000,http://localhost:3001"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    
  async:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 100
    thread-name-prefix: "AsyncExecutor-"

logging:
  level:
    com.arbmonitor: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE